config/routes.rb
Rails.application.routes.draw do
  resources :memberships

  resources :payments

  resources :people_groups

  resources :groups

  resources :functions

  resources :areas

  resources :people_skills

  resources :skills

  resources :people
  root 'index#home'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}  # The priority is based upon order of creation: first created -> highest priority.
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/function.rb
class Function < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :area
  belongs_to :function
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :person
  belongs_to :area
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :person
end

app/models/people_group.rb
class PeopleGroup < ActiveRecord::Base
  belongs_to :person
  belongs_to :group
end

app/models/people_skill.rb
class PeopleSkill < ActiveRecord::Base
  belongs_to :person
  belongs_to :skill

  validates_presence_of :level
  validates :level, :inclusion => {:in => [1,3]}
  validates_presence_of :favor
  validates :favor, :inclusion => {:in => [1,3]}
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :people_skills, foreign_key: :person_id
  has_many :skills, through: :people_skills

  validates_presence_of :name, :message => "Nemas jmeno"


  def not_my_skills
    my_skills_ids = skills.ids
    Skill.where.not(id:my_skills_ids)
  end
  
  def full_name
    "#{degree} #{name} #{surname} #{degree2}"
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :people_skills
  has_many :people, through: :people_skills


  def not_my_people
    my_people_ids = people.ids
    Person.where.not(id:my_people_ids)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
#  has_paper_trail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:open_id]
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :twitter]

  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token['user_info']
    if user = User.find_by(openid_identifier: access_token.uid)
      user
    else #  Create a user with a stub password.
      User.create!(:openid_identifier => access_token.uid, :name => access_token.info.name, :email => access_token.info.email)
    end
  end

  def ability
    @ability ||= Ability.new(self)
  end
  delegate :can?, :cannot?, :to => :ability

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @areas = Area.all
    respond_with(@areas)
  end

  def show
    respond_with(@area)
  end

  def new
    @area = Area.new
    respond_with(@area)
  end

  def edit
  end

  def create
    @area = Area.new(area_params)
    @area.save
    respond_with(@area)
  end

  def update
    @area.update(area_params)
    respond_with(@area)
  end

  def destroy
    @area.destroy
    respond_with(@area)
  end

  private
    def set_area
      @area = Area.find(params[:id])
    end

    def area_params
      params.require(:area).permit(:parent_id, :name, :note)
    end
end

app/controllers/index_controller.rb
class IndexController < ActionController::Base
  def home
    if user_signed_in?
      redirect_to controller: 'people', action: 'index'
    else
      render :home, layout: 'application'
    end

  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @memberships = Membership.all
    respond_with(@memberships)
  end

  def show
    respond_with(@membership)
  end

  def new
    @membership = Membership.new
    respond_with(@membership)
  end

  def edit
  end

  def create
    @membership = Membership.new(membership_params)
    @membership.save
    respond_with(@membership)
  end

  def update
    @membership.update(membership_params)
    respond_with(@membership)
  end

  def destroy
    @membership.destroy
    respond_with(@membership)
  end

  private
    def set_membership
      @membership = Membership.find(params[:id])
    end

    def membership_params
      params.require(:membership).permit(:user_id, :date_applied, :date_voted, :date_paid, :date_begin, :date_end, :voted, :area_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/people_groups_helper.rb
module PeopleGroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/memberships/_form.html.haml
= form_for @membership do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2= "#{pluralize(@membership.errors.count, "error")} prohibited this membership from being saved:"
      %ul
        - @membership.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.hidden_field :person_id
  .field
    = f.label :date_applied
    = f.date_select :date_applied
  .field
    = f.label :date_voted
    = f.date_select :date_voted
  .field
    = f.label :date_paid
    = f.date_select :date_paid
  .field
    = f.label :date_begin
    = f.date_select :date_begin
  .field
    = f.label :date_end
    = f.date_select :date_end
  .field
    = f.label :voted
    = f.text_field :voted
  .field
    = f.label :area_id
    = f.collection_select :area_id, Area.all, :id, :name
  .actions
    = f.submit 'Uložit'

app/views/memberships/edit.html.haml
%h1 Editing membership

= render 'form'

= link_to 'Show', @membership
\|
= link_to 'Back', memberships_path

app/views/memberships/index.html.haml
%h1 Listing memberships

%table
  %thead
    %tr
      %th User
      %th Date applied
      %th Date voted
      %th Date paid
      %th Date begin
      %th Date end
      %th Voted
      %th Area
      %th
      %th
      %th

  %tbody
    - @memberships.each do |membership|
      %tr
        %td= membership.user_id
        %td= membership.date_applied
        %td= membership.date_voted
        %td= membership.date_paid
        %td= membership.date_begin
        %td= membership.date_end
        %td= membership.voted
        %td= membership.area_id
        %td= link_to 'Show', membership
        %td= link_to 'Edit', edit_membership_path(membership)
        %td= link_to 'Destroy', membership, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Membership', new_membership_path

app/views/memberships/new.html.haml
%h1 New membership

= render 'form'

= link_to 'Back', memberships_path

app/views/memberships/show.html.haml
%p#notice= notice

%p
  %b User:
  = @membership.user_id
%p
  %b Date applied:
  = @membership.date_applied
%p
  %b Date voted:
  = @membership.date_voted
%p
  %b Date paid:
  = @membership.date_paid
%p
  %b Date begin:
  = @membership.date_begin
%p
  %b Date end:
  = @membership.date_end
%p
  %b Voted:
  = @membership.voted
%p
  %b Area:
  = @membership.area_id

= link_to 'Edit', edit_membership_path(@membership)
\|
= link_to 'Back', memberships_path