config/routes.rb
Rails.application.routes.draw do
  resources :memberships

  resources :payments

  resources :people_groups

  resources :groups

  resources :functions

  resources :areas

  resources :people_skills

  resources :skills

  resources :people
  root 'index#home'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}  # The priority is based upon order of creation: first created -> highest priority.
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/function.rb
class Function < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :area
  belongs_to :function
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :person
  belongs_to :area
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :person
end

app/models/people_group.rb
class PeopleGroup < ActiveRecord::Base
  belongs_to :person
  belongs_to :group
end

app/models/people_skill.rb
class PeopleSkill < ActiveRecord::Base
  belongs_to :person
  belongs_to :skill

  validates_presence_of :level
  validates :level, :inclusion => {:in => [1,3]}
  validates_presence_of :favor
  validates :favor, :inclusion => {:in => [1,3]}
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :people_skills, foreign_key: :person_id
  has_many :skills, through: :people_skills

  validates_presence_of :name, :message => "Nemas jmeno"


  def not_my_skills
    my_skills_ids = skills.ids
    Skill.where.not(id:my_skills_ids)
  end
  
  def full_name
    "#{degree} #{name} #{surname} #{degree2}"
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :people_skills
  has_many :people, through: :people_skills


  def not_my_people
    my_people_ids = people.ids
    Person.where.not(id:my_people_ids)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
#  has_paper_trail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:open_id]
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :twitter]

  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token['user_info']
    if user = User.find_by(openid_identifier: access_token.uid)
      user
    else #  Create a user with a stub password.
      User.create!(:openid_identifier => access_token.uid, :name => access_token.info.name, :email => access_token.info.email)
    end
  end

  def ability
    @ability ||= Ability.new(self)
  end
  delegate :can?, :cannot?, :to => :ability

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @areas = Area.all
    respond_with(@areas)
  end

  def show
    respond_with(@area)
  end

  def new
    @area = Area.new
    respond_with(@area)
  end

  def edit
  end

  def create
    @area = Area.new(area_params)
    @area.save
    respond_with(@area)
  end

  def update
    @area.update(area_params)
    respond_with(@area)
  end

  def destroy
    @area.destroy
    respond_with(@area)
  end

  private
    def set_area
      @area = Area.find(params[:id])
    end

    def area_params
      params.require(:area).permit(:parent_id, :name, :note)
    end
end

app/controllers/index_controller.rb
class IndexController < ActionController::Base
  def home
    if user_signed_in?
      redirect_to controller: 'people', action: 'index'
    else
      render :home, layout: 'application'
    end

  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :check_permission

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:nick, :degree, :name, :surname, :degree2, :street, :town, :zip, :birth, :email, :phone, :jabber)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/people_groups_helper.rb
module PeopleGroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/people/_form.html.haml
= form_for(@person) do |f|
  - if @person.errors.any?
    #error_explanation
      %h2
        = pluralize(@person.errors.count, "error")
        prohibited this person from being saved:
      %ul
        - @person.errors.full_messages.each do |message|
          %li= message
  %fieldset
    %legend &nbsp;Identita&nbsp;
    .field
      = f.label :nick
      %br/
      = f.text_field :nick
    .field
      = f.label :degree, "titul před "
      %br/
      = f.text_field :degree
    .field
      = f.label :name, "Jméno "
      %br/
      = f.text_field :name
    .field
      = f.label :surname, "Příjmení "
      %br/
      = f.text_field :surname
    .field
      = f.label :degree2, "titul za "
      %br/
      = f.text_field :degree2
    .field
      = f.label :birth, "Narození "
      %br/
      = f.date_select :birth, :start_year => 1920, :end_year => Time.now.year-17, :include_blank => true
  %fieldset
    %legend &nbsp;Bydliště&nbsp;
    .field
      = f.label :street, "Ulice a číslo "
      %br/
      = f.text_field :street
    .field
      = f.label :town, "Město/obec "
      %br/
      = f.text_field :town
    .field
      = f.label :zip, "PSČ (mezeru vložit ručně)"
      %br/
      = f.text_field :zip
  %fieldset
    %legend &nbsp;Kontakt&nbsp;
    .field
      = f.label :email, "e-mail "
      %br/
      = f.text_field :email
    .field
      = f.label :phone, "telefon "
      %br/
      = f.text_field :phone
    .field
      = f.label :jabber
      %br/
      = f.text_field :jabber
  %fieldset
    %legend &nbsp;Mentorství&nbsp;
    .field
      = f.label :ask, "je sám mentor"
      = f.check_box :is_mentor
      /.field
      /  = f.label :skill_id
      /  = f.collection_select(:skill_id, @people_skill.person.not_my_skills, :id, :name)
      /  = f.hidden_field :person_id

  .actions
    = f.submit "Uložit"

app/views/people/edit.html.haml
%h1 Editace osobních údajů
= render 'form'
= link_to 'Detaily osoby', @person
|
\#{link_to 'Seznam osob', people_path}

app/views/people/index.html.haml
%h1 Seznam osob - dobrovolníků
- if @people.count==0
  %div.nula
    Nejsou žádné osoby odpovídající podmínkám. Můžete přidat nové.
- else
  %table
    %thead
      %tr
        %th osoba
        %th #
        %th nick
        %th ulice č.
        %th město/obec
        %th PSČ
        %th narození
        %th e-mail
        %th telefon
        %th jabber
        %th{:colspan => "2"}
    %tbody
      - @people.each do |person|
        %tr
          %td= link_to person.full_name, person
          %td= person.people_skills.count
          %td= person.nick
          %td= person.street
          %td= person.town
          %td= person.zip
          %td= person.birth
          %td= person.email
          %td= person.phone
          %td= person.jabber
          %td= link_to 'Edit', edit_person_path(person)
          /%td= link_to 'x', person, method: :delete, data: { confirm: 'Opravdu smazat osobu jménem '+person.full_name+'?' }

%br/
%div.new
  = link_to 'přidat novou osobu', new_person_path

app/views/people/new.html.haml
%h1 Přidání nové osoby
= render 'form'
= link_to 'Seznam osob', people_path

app/views/people/show.html.haml
%p#notice= notice
%h2
  = @person.full_name
  %span.edit
    = link_to 'Edit os. údajů', edit_person_path(@person)
%p
  %strong Nick:
  = @person.nick
%p
  %strong Titul:
  = @person.degree
%p
  %strong Jméno:
  = @person.name
%p
  %strong Příjmení:
  = @person.surname
%p
  %strong Titul za:
  = @person.degree2
%p
  %strong Ulice a číslo:
  = @person.street
%p
  %strong Město/obec:
  = @person.town
%p
  %strong PSČ (Zip):
  = @person.zip
%p
  %strong Narozen(a):
  = @person.birth
%p
  %strong Email:
  = @person.email
%p
  %strong Telefon:
  = @person.phone
%p
  %strong Jabber:
  = @person.jabber
- if @person.people_skills.count==0
  %div.nula
    Tato osoba nemá zatím žádnou dovednost. Můžete nějaké přidat.
- else

  %h3 Dovednosti
  %table
    %tr
      %th Název dovednosti
      %th Úroveň
      %th Čas/ochota
      %th nastav
      %th Poznámka
      %th{:colspan => "2"}
    - @person.people_skills.each do |skill|
      %tr
        %td= link_to skill.skill.name, skill.skill
        %td
          - skill.level.times do |l|
            %span.fa.fa-star
        %td
          - skill.favor.times do |f|
            %span.fa.fa-heart
        %td= link_to 'Změnit', edit_people_skill_path(skill)
        %td=skill.note
        %td
        %td= link_to 'x', skill, :method => :delete, :data => { :confirm => 'osoba '+@person.full_name+'nemá dovednost '+skill.skill.name+'?' }
      
%br
- if @person.not_my_skills.count>0
  %div.dal
    = link_to 'Přidat dovednost', new_people_skill_path(:people_id => @person.id)
/|
/\#{link_to 'Seznam osob', people_path}