config/routes.rb
Rails.application.routes.draw do
  resources :memberships

  resources :payments

  resources :people_groups

  resources :groups

  resources :functions

  resources :areas

  resources :people_skills

  resources :skills

  resources :people
  root 'index#home'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}  # The priority is based upon order of creation: first created -> highest priority.
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/function.rb
class Function < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :area
  belongs_to :function
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :person
  belongs_to :area
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :person
end

app/models/people_group.rb
class PeopleGroup < ActiveRecord::Base
  belongs_to :person
  belongs_to :group
end

app/models/people_skill.rb
class PeopleSkill < ActiveRecord::Base
  belongs_to :person
  belongs_to :skill

  validates_presence_of :level
  validates :level, :inclusion => {:in => [1,3]}
  validates_presence_of :favor
  validates :favor, :inclusion => {:in => [1,3]}
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :people_skills, foreign_key: :person_id
  has_many :skills, through: :people_skills

  validates_presence_of :name, :message => "Nemas jmeno"


  def not_my_skills
    my_skills_ids = skills.ids
    Skill.where.not(id:my_skills_ids)
  end
  
  def full_name
    "#{degree} #{name} #{surname} #{degree2}"
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :people_skills
  has_many :people, through: :people_skills


  def not_my_people
    my_people_ids = people.ids
    Person.where.not(id:my_people_ids)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
#  has_paper_trail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:open_id]
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :twitter]

  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token['user_info']
    if user = User.find_by(openid_identifier: access_token.uid)
      user
    else #  Create a user with a stub password.
      User.create!(:openid_identifier => access_token.uid, :name => access_token.info.name, :email => access_token.info.email)
    end
  end

  def ability
    @ability ||= Ability.new(self)
  end
  delegate :can?, :cannot?, :to => :ability

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @areas = Area.all
    respond_with(@areas)
  end

  def show
    respond_with(@area)
  end

  def new
    @area = Area.new
    respond_with(@area)
  end

  def edit
  end

  def create
    @area = Area.new(area_params)
    @area.save
    respond_with(@area)
  end

  def update
    @area.update(area_params)
    respond_with(@area)
  end

  def destroy
    @area.destroy
    respond_with(@area)
  end

  private
    def set_area
      @area = Area.find(params[:id])
    end

    def area_params
      params.require(:area).permit(:parent_id, :name, :note)
    end
end

app/controllers/index_controller.rb
class IndexController < ActionController::Base
  def home
    if user_signed_in?
      redirect_to controller: 'people', action: 'index'
    else
      render :home, layout: 'application'
    end

  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  before_action :check_permission

  respond_to :html

  def index
    @skills = Skill.all
    respond_with(@skills)
  end

  def show
    respond_with(@skill)
  end

  def new
    @skill = Skill.new
    respond_with(@skill)
  end

  def edit
  end

  def create
    @skill = Skill.new(skill_params)
    @skill.save
    respond_with(@skill)
  end

  def update
    @skill.update(skill_params)
    respond_with(@skill)
  end

  def destroy
    @skill.destroy
    respond_with(@skill)
  end

  private
    def set_skill
      @skill = Skill.find(params[:id])
    end

    def skill_params
      params.require(:skill).permit(:name, :ask)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/people_groups_helper.rb
module PeopleGroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.haml
= form_for @skill do |f|
  - if @skill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@skill.errors.count, "error")} prohibited this skill from being saved:"
      %ul
        - @skill.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name, "název "
    = f.text_field :name
  .field
    = f.label :ask, "dotazníková "
    = f.check_box :ask
  .actions
    = f.submit 'Uložit'

app/views/skills/edit.html.haml
%h1= "Editace " + @skill.name

= render 'form'

= link_to 'Kdo umí ' + @skill.name + '? ', @skill
\|
= link_to ' Seznam dovedností', skills_path

app/views/skills/index.html.haml
%h1 Seznam dovedností

- if @skills.count==0
  %div.nula
    Nejsou žádné dovednosti odpovídající podmínkám. Můžete vytvořit nové.
-else
  %table
    %thead
      %tr
        %th Dovednost
        %th dotazníková
        %th lidí
        %td upravit

    %tbody
      - @skills.each do |skill|
        %tr
          %td= link_to skill.name, skill
          %td
            - if skill.ask
              %span.fa.fa-check
          %td= skill.people_skills.count
          %td
            = link_to edit_skill_path(skill) do
              %span.fa.fa-gear
          /%td= link_to 'x', skill, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br/
%div.new
  = link_to 'Vytvořit novou dovednost', new_skill_path

app/views/skills/new.html.haml
%h1 New skill

= render 'form'

= link_to 'Back', skills_path

app/views/skills/show.html.haml
%p#notice= notice

%h2
  Dovednost:
  = @skill.name
  %span.edit
    = link_to 'editovat', edit_skill_path(@skill)

%p
  - if @skill.ask
    %b Dotazníková
  - else 
    není dotazníková
- if @skill.people_skills.count==0
  %div.nula
    Nejsou zadáni žádní dobrovolníci. Můžete nějaké nalézt v seznamu a zadat.
- else
  %table
    %tr
      %th dobrovolník
      %th úroveň
      %th čas/ochota
      %th nastav
      %th doplnění
      %th telefon
      %th email
      %th jabber
      %th město
    - @skill.people_skills.each do |ps|
      %tr
        %td= link_to ps.person.full_name, ps.person
        %td
          - ps.level.times do |l|
            %span.fa.fa-star
        %td
          - ps.favor.times do |f|
            %span.fa.fa-heart
        %td= link_to 'o', edit_people_skill_path(ps)
        %td=ps.note
        %td=ps.person.phone
        %td=ps.person.email
        %td=ps.person.jabber
        %td=ps.person.town

%br
%div.dal
  = link_to 'Přidat dobrovolníka k dovednosti', new_people_skill_path(:skill_id => @skill.id)
%br
%div.new
  = link_to 'Vytvořit novou dovednost', new_skill_path