config/routes.rb
Rails.application.routes.draw do
  resources :memberships

  resources :payments

  resources :people_groups

  resources :groups

  resources :functions

  resources :areas

  resources :people_skills

  resources :skills

  resources :people
  root 'index#home'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}  # The priority is based upon order of creation: first created -> highest priority.
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/function.rb
class Function < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :area
  belongs_to :function
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :person
  belongs_to :area
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :person
end

app/models/people_group.rb
class PeopleGroup < ActiveRecord::Base
  belongs_to :person
  belongs_to :group
end

app/models/people_skill.rb
class PeopleSkill < ActiveRecord::Base
  belongs_to :person
  belongs_to :skill

  validates_presence_of :level
  validates :level, :inclusion => {:in => [1,3]}
  validates_presence_of :favor
  validates :favor, :inclusion => {:in => [1,3]}
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :people_skills, foreign_key: :person_id
  has_many :skills, through: :people_skills

  validates_presence_of :name, :message => "Nemas jmeno"


  def not_my_skills
    my_skills_ids = skills.ids
    Skill.where.not(id:my_skills_ids)
  end
  
  def full_name
    "#{degree} #{name} #{surname} #{degree2}"
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :people_skills
  has_many :people, through: :people_skills


  def not_my_people
    my_people_ids = people.ids
    Person.where.not(id:my_people_ids)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
#  has_paper_trail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:open_id]
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :twitter]

  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token['user_info']
    if user = User.find_by(openid_identifier: access_token.uid)
      user
    else #  Create a user with a stub password.
      User.create!(:openid_identifier => access_token.uid, :name => access_token.info.name, :email => access_token.info.email)
    end
  end

  def ability
    @ability ||= Ability.new(self)
  end
  delegate :can?, :cannot?, :to => :ability

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @areas = Area.all
    respond_with(@areas)
  end

  def show
    respond_with(@area)
  end

  def new
    @area = Area.new
    respond_with(@area)
  end

  def edit
  end

  def create
    @area = Area.new(area_params)
    @area.save
    respond_with(@area)
  end

  def update
    @area.update(area_params)
    respond_with(@area)
  end

  def destroy
    @area.destroy
    respond_with(@area)
  end

  private
    def set_area
      @area = Area.find(params[:id])
    end

    def area_params
      params.require(:area).permit(:parent_id, :name, :note)
    end
end

app/controllers/index_controller.rb
class IndexController < ActionController::Base
  def home
    if user_signed_in?
      redirect_to controller: 'people', action: 'index'
    else
      render :home, layout: 'application'
    end

  end
end

app/controllers/people_skills_controller.rb
class PeopleSkillsController < ApplicationController
  before_action :set_people_skill, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @people_skills = PeopleSkill.all
    respond_with(@people_skills)
  end

  def show
    respond_with(@people_skill)
  end

  def new
    @people_skill = PeopleSkill.new
    if !params[:people_id].nil?
      @people_skill.person = Person.find(params[:people_id])
    end

    if !params[:skill_id].nil?
      @people_skill.skill = Skill.find(params[:skill_id])
    end

    respond_with(@people_skill)
  end

  def edit
    @people_skill.level ||= 1
    @people_skill.favor ||= 1
  end

  def create
    @people_skill = PeopleSkill.new(people_skill_params)
    @people_skill.save

    redirect_to @people_skill.person
  end

  def update
    @people_skill.update(people_skill_params)
    redirect_to @people_skill.person
  end

  def destroy
    person = @people_skill.person
    @people_skill.destroy
    redirect_to person
  end

  private
    def set_people_skill
      @people_skill = PeopleSkill.find(params[:id])
    end

    def people_skill_params
      params.require(:people_skill).permit(:person_id, :skill_id, :favor, :level, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/people_skills_helper.rb
module PeopleSkillsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/people_skills/_form.html.haml
= form_for @people_skill do |f|
  - if @people_skill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@people_skill.errors.count, "error")} prohibited this people_skill from being saved:"
      %ul
        - @people_skill.errors.full_messages.each do |msg|
          %li= msg

  - if @people_skill.id.nil?
    .field
      - if @people_skill.skill.nil?
        = f.label :skill_id
        = f.collection_select(:skill_id, @people_skill.person.not_my_skills, :id, :name)
        = f.hidden_field :person_id
      - else
        = f.label :people_id
        = f.collection_select(:person_id, @people_skill.skill.not_my_people, :id, :full_name)
        = f.hidden_field :skill_id
  - else
    %h3= 'dovednost '+ @people_skill.skill.name
  .field
    = f.label :level, "úroveň (začátečník, střední, expert)"
    = f.number_field :level
  .field
    = f.label :favor, "čas (možnosti, ochota)"
    = f.number_field :favor
  .field
    = f.label :note, "doplnění k dovednosti"
    = f.text_field :note
  .actions
    = f.submit 'Uložit'

app/views/people_skills/edit.html.haml
%h2= @people_skill.person.full_name

= render 'form'

= link_to 'Zpět na osobu ' + @people_skill.person.full_name, @people_skill.person

app/views/people_skills/index.html.haml
%h1 Listing people_skills

%table
  %thead
    %tr
      %th People
      %th Skill
      %th Favor
      %th Level
      %th Note
      %th
      %th
      %th
      
  %tbody
    - @people_skills.each do |people_skill|
      %tr
        %td= people_skill.people_id
        %td= people_skill.skill_id
        %td= people_skill.favor
        %td= people_skill.level
        %td= people_skill.note
        %td= link_to 'Show', people_skill
        %td= link_to 'Edit', edit_people_skill_path(people_skill)
        %td= link_to 'Destroy', people_skill, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New People skill', new_people_skill_path

app/views/people_skills/new.html.haml
- if @people_skill.person
  %h2= @people_skill.person.full_name
  %p
    %strong přidat dovednost

- if @people_skill.skill
  %h2= @people_skill.skill.name
  %p
    %strong přidat dobrovolníka

= render 'form'

- if @people_skill.person
  = link_to 'Zpět na osobu ' + @people_skill.person.full_name, @people_skill.person

- if @people_skill.skill
  = link_to 'Zpět na dovednost ' + @people_skill.skill.name, @people_skill.skill

app/views/people_skills/show.html.haml
%p#notice= notice

%p
  %b People:
  = @people_skill.person_id
%p
  %b Skill:
  = @people_skill.skill_id
%p
  %b Favor:
  = @people_skill.favor
%p
  %b Level:
  = @people_skill.level
%p
  %b Note:
  = @people_skill.note

= link_to 'Edit', edit_people_skill_path(@people_skill)
\|
= link_to 'Back', people_skills_path